import CustomTabBar from './custom-tab-bar'
import Pagination from './pagination'
import SpecialTip from './special-tip'
import VanCellGroup from '@vant/weapp/dist/cell-group'
import VanCell from '@vant/weapp/dist/cell'
import VanDialog from '@vant/weapp/dist/dialog'
import VanNoticeBar from '@vant/weapp/dist/notice-bar'
import VanSearch from '@vant/weapp/dist/search'
import VanButton from '@vant/weapp/dist/button'
import VanLoading from '@vant/weapp/dist/loading'
import VanDivider from '@vant/weapp/dist/divider'
import VanNotify from '@vant/weapp/dist/notify'
import VanPanel from '@vant/weapp/dist/panel'
import VanField from '@vant/weapp/dist/field'
import VanIndexBar from '@vant/weapp/dist/index-bar'
import VanIndexAnchor from '@vant/weapp/dist/index-anchor'
import Dialog from '@vant/weapp/dist/dialog/dialog'
import Notify from '@vant/weapp/dist/notify/notify'

export { CustomTabBar, Pagination, SpecialTip }
